server:
  port: 8090

spring:
  redis:
    host: 127.0.0.1
    port: 6379

tencent:
  sms:
    secretId: AKID8FGc0ELTVOyOcdS9ew3x0tZ4SkqmUxBC
    secretKey: vd6NTvBN4buzPehgXCdtwjKuGOIyQdcx
    appId: 1400671597

contract:
  credentials:








